### ISSUE TITLE
Initial TODO items.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/guides#1]
- [ ] Rails style guide see https://github.com/bbatsov/rails-style-guide
- [ ] Bugzilla how-to
  - how to copy commit details / clone a ticket
- [ ] Git how-to
  - reword a commit
  - amend a commit
  - squashing
  - reordering
  - deleting a commit
  - uncommit a file from an existing commit
- [ ] Move CFME-specific stuff into CFME proper
  - logs
  - error collection
- [ ] Create CONTRIBUTING.md files on other open source projects that reference this guide.  Mirror the one in CFME.
